# Generated by Django 5.1.8 on 2025-05-03 06:50

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_section", 5), ("code", 8), ("raw_html", 1)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: ("wagtail.blocks.TextBlock", (), {}),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StreamBlock",
                        [[("heading", 0), ("paragraph", 1), ("image", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "python", "required": True},
                    ),
                    7: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 6), ("code", 7)]],
                        {},
                    ),
                },
                default=[
                    (
                        "content_section",
                        [
                            ("heading", "Your Heading Here"),
                            ("paragraph", "Start writing your content here..."),
                        ],
                    )
                ],
            ),
        ),
    ]
