# Generated by Django 5.1.8 on 2025-05-03 06:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("content_section", 6), ("code", 9), ("raw_html", 2)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Add a subheading (optional)", "required": False},
                    ),
                    2: ("wagtail.blocks.TextBlock", (), {}),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 3), ("caption", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 0),
                                ("subheading", 1),
                                ("paragraph", 2),
                                ("image", 5),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "python", "required": True},
                    ),
                    8: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("language", 7), ("code", 8)]],
                        {},
                    ),
                },
                default=[
                    (
                        "content_section",
                        [
                            ("heading", "Your Heading Here"),
                            ("subheading", "Your Subheading Here"),
                            ("paragraph", "Start writing your content here..."),
                        ],
                    )
                ],
            ),
        ),
    ]
